### PR TITLE
adding logClust to leaf node

### PR DESCRIPTION
**Pull request by JoeHitHard**
When there is only one token in the logClust.logTemplate add logClust to Node
Drain.py line no. 143

### CODE REVIEW

**Comment by jimzhu** [comment]
Thanks for your pull request. You need split your commits since the last two has been merged. Besides, you need to edit the minimal lines only, but not make changes +337 −331 (lines). It is hard to determine your changes made.

**Comment by JoeHitHard** [comment]
i changed only 2 lines, i guess there is a problem with my PyCharm have to check it.

**Comment by JoeHitHard** [comment]
i made changes only at 
`Drain.py` line no. `143`

**Comment by jimzhu** [comment]
Could you pls explain your changes in detail? Are there any test cases?

**Pull request closed without merging**
